---
- name: Add stream-api user
  user:
    name: stream-api
    home: /opt/stream-api/
    state: present

- name: install additional dependencies
  apt:
    package: python3-passlib
    state: latest

- name: create rtmp-auth directory
  file:
    path: /opt/voc/
    state: directory

- name: copy rtmp-auth binary
  copy:
    src: rtmp-auth
    dest: /opt/voc/
    mode: 0755
  register: ingest_rtmp_auth_bin

- name: add rtmp-auth service file
  template:
    src: rtmp-auth.service.j2
    dest: /etc/systemd/system/rtmp-auth.service
  register: ingest_rtmp_auth_service

- name: enable rtmp-auth service
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: rtmp-auth
  when: ingest_rtmp_auth_bin.changed or ingest_rtmp_auth_service.changed