---
  - name: restart nginx
    service: name=nginx state=restarted
    when: nginx is defined and nginx == 'yes'

  - name: reload nginx
    service: name=nginx state=reloaded
    when: nginx is defined and nginx == 'yes'
